name: GitHub Actions Update Package.json
on: 
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 * * 1

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: duplessi.geoffrey@gmail.com
        AUTHOR_NAME: Grezor
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.UPDATE }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
    